CREATE TABLE hoteis (
  id INTEGER NOT NULL AUTO_INCREMENT,
  nome VARCHAR(250) NOT NULL,
  telefone VARCHAR(100) NULL,
  observacoes VARCHAR(300) NULL,
  PRIMARY KEY (id)
  );

CREATE TABLE colaboradores (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(250) NOT NULL,
  id_hotel INTEGER NULL,
  ativo varchar(1) NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_hotel) REFERENCES hoteis(id)
  );

INSERT INTO hoteis (nome,telefone) VALUES ('3286', '7006');
INSERT INTO hoteis (nome,telefone) VALUES ('Aardvark Inn', '3286-0806');
INSERT INTO hoteis (nome,telefone) VALUES ('Acácia Negra', '3286-2830');
INSERT INTO hoteis (nome,telefone) VALUES ('Aconchego da Serra', '3286-2061');
INSERT INTO hoteis (nome,telefone) VALUES ('Aeroporto POA', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Agência', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Águas Claras', '3286-6044');
INSERT INTO hoteis (nome,telefone) VALUES ('Águia Branca', '3286-1501');
INSERT INTO hoteis (nome,telefone) VALUES ('Alameda Paradiso', '3295-1515');
INSERT INTO hoteis (nome,telefone) VALUES ('Albergo di Bezzi Pousada', '3286-4400');
INSERT INTO hoteis (nome,telefone) VALUES ('Ald Mamma', '3286-1855');
INSERT INTO hoteis (nome,telefone) VALUES ('Aldeia das Azaleias (Antigo Hotel Irmscher)', '3286-2006');
INSERT INTO hoteis (nome,telefone) VALUES ('Aldeia dos Sonhos', '3282-0000');
INSERT INTO hoteis (nome,telefone) VALUES ('Alegria', '3286-1556');
INSERT INTO hoteis (nome,telefone) VALUES ('Aline Ville', '3282-2039');
INSERT INTO hoteis (nome,telefone) VALUES ('Alpenhaus Gramado', '3295-9000');
INSERT INTO hoteis (nome,telefone) VALUES ('Alpenhof', '3286-2055');
INSERT INTO hoteis (nome,telefone) VALUES ('Alpes Verdes', '3282-1162');
INSERT INTO hoteis (nome,telefone) VALUES ('Alpestre', '3286-1311');
INSERT INTO hoteis (nome,telefone) VALUES ('Alta Vista', '3282-0060');
INSERT INTO hoteis (nome,telefone) VALUES ('Amore Mio', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Anjos', '3282-7164 / 3282-9308');
INSERT INTO hoteis (nome,telefone) VALUES ('Apartamento João Carlos', 'Rua Maranhão');
INSERT INTO hoteis (nome,telefone) VALUES ('Apto Cleiton', 'Nº 107');
INSERT INTO hoteis (nome,telefone) VALUES ('Arc-En-Ciel', '3298-3231');
INSERT INTO hoteis (nome,telefone) VALUES ('Ares da Serra', '3286-4534');
INSERT INTO hoteis (nome,telefone) VALUES ('Árvore da Coruja (antigo Albergo Di Bezzi)- 3286-4400', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Assefaz', '3286-2020');
INSERT INTO hoteis (nome,telefone) VALUES ('Avenida', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Azaléia', '3286-3583');
INSERT INTO hoteis (nome,telefone) VALUES ('Bangalôs da Serra', '3286-1737');
INSERT INTO hoteis (nome,telefone) VALUES ('Barbacovi', '3286-2370');
INSERT INTO hoteis (nome,telefone) VALUES ('Bavária', '3286-1362');
INSERT INTO hoteis (nome,telefone) VALUES ('Beija-Flor', '3286-3025 / 9645-9533');
INSERT INTO hoteis (nome,telefone) VALUES ('Bela Vista Flats', '3286-9369');
INSERT INTO hoteis (nome,telefone) VALUES ('Bella Terra', '3286-3333');
INSERT INTO hoteis (nome,telefone) VALUES ('Belluno', '3286-0820');
INSERT INTO hoteis (nome,telefone) VALUES ('Bernardete', '3286-1569');
INSERT INTO hoteis (nome,telefone) VALUES ('Bertoluci', '3286-1911');
INSERT INTO hoteis (nome,telefone) VALUES ('Betânia', '3286-1739');
INSERT INTO hoteis (nome,telefone) VALUES ('Binas Haus-Nova Petrópolis', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Blumemberg', '3282-2939');
INSERT INTO hoteis (nome,telefone) VALUES ('Brisa da Serra', '3286-4386');
INSERT INTO hoteis (nome,telefone) VALUES ('Brisa de Gramado', '3286-6788');
INSERT INTO hoteis (nome,telefone) VALUES ('Cabana Jardim de Flores', '3286-1315');
INSERT INTO hoteis (nome,telefone) VALUES ('Cabanas Alto da Serra', '3282-2133');
INSERT INTO hoteis (nome,telefone) VALUES ('Cabanas Belo Destino', '3286-1391');
INSERT INTO hoteis (nome,telefone) VALUES ('Cabanas da Mata', '3286-2271');
INSERT INTO hoteis (nome,telefone) VALUES ('Cabanas Rota do Sol', '3286-6569');
INSERT INTO hoteis (nome,telefone) VALUES ('Cabanas Tio Chico', '3286-1327');
INSERT INTO hoteis (nome,telefone) VALUES ('Cabanas Tio Müller', '3286-2508');
INSERT INTO hoteis (nome,telefone) VALUES ('Caminho das Rosas (54) 3422-0123', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Caminho de La Serra', 'Canela');
INSERT INTO hoteis (nome,telefone) VALUES ('Camping Gramado', '3286-2615');
INSERT INTO hoteis (nome,telefone) VALUES ('Cantinho do Sossego', '3286-5642');
INSERT INTO hoteis (nome,telefone) VALUES ('Canto Belo', '3286-2750');
INSERT INTO hoteis (nome,telefone) VALUES ('Canto Doce', '3286-3807');
INSERT INTO hoteis (nome,telefone) VALUES ('Canto Verde', '3286-1961');
INSERT INTO hoteis (nome,telefone) VALUES ('Caracol', '3282-4030');
INSERT INTO hoteis (nome,telefone) VALUES ('Caroline', '3286-6398');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa Branca', '3286-2552');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa D. Alice', '3286 2096');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa D. Julieta', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa da Juventude', '3286-1811');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa da Montanha', '3295-7575');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa de Veneza', '3295-2333');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa Dona Lurdes 32865739', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa João Carlos', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa Rosa', '3282-2400');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa Tia Iracema', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Casa Tia Vera', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Cavalo Branco', '3286-1254');
INSERT INTO hoteis (nome,telefone) VALUES ('Celita', '3286-2824');
INSERT INTO hoteis (nome,telefone) VALUES ('Chalé da Montanha', '3286');
INSERT INTO hoteis (nome,telefone) VALUES ('Chalé dos Plátanos (Stephanie)', '9603-0640');
INSERT INTO hoteis (nome,telefone) VALUES ('Chalé Recanto do Lago', '3286-0971');
INSERT INTO hoteis (nome,telefone) VALUES ('Chalés Fioreze', '9999-7557');
INSERT INTO hoteis (nome,telefone) VALUES ('Chalets do Vale', '3286-4151');
INSERT INTO hoteis (nome,telefone) VALUES ('Colina', '3286-7355');
INSERT INTO hoteis (nome,telefone) VALUES ('Colina de Pedra Hotel Pousada', '3286-0967');
INSERT INTO hoteis (nome,telefone) VALUES ('Condominio Laje de Pedra', '3278-9000');
INSERT INTO hoteis (nome,telefone) VALUES ('Continental', '3282-5610');
INSERT INTO hoteis (nome,telefone) VALUES ('Convention Bureau', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Coração da Mata', '9906-5406');
INSERT INTO hoteis (nome,telefone) VALUES ('Das Flores', '3286-1841');
INSERT INTO hoteis (nome,telefone) VALUES ('Di Marco', '3286-3394');
INSERT INTO hoteis (nome,telefone) VALUES ('Don Ramon', '3282-3306');
INSERT INTO hoteis (nome,telefone) VALUES ('Due Fratelli', '3286-5225');
INSERT INTO hoteis (nome,telefone) VALUES ('Encantos Charme Hotel', '3286-9494');
INSERT INTO hoteis (nome,telefone) VALUES ('Encantos da Terra', '3282-2080');
INSERT INTO hoteis (nome,telefone) VALUES ('Encantos de Gramado', '3286-3248');
INSERT INTO hoteis (nome,telefone) VALUES ('Encantos do Sul', '3286-9446');
INSERT INTO hoteis (nome,telefone) VALUES ('Encantos Lago Hotel', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Encantos Lago Hotel', '3286.5225');
INSERT INTO hoteis (nome,telefone) VALUES ('Encosta', '3286-3488');
INSERT INTO hoteis (nome,telefone) VALUES ('Endereço em Canela', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Endereço em Canela', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Endereço em Caxias', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Endereço em Gramado', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Endereço em POA', '');
INSERT INTO hoteis (nome,telefone) VALUES ('ESTAÇÃO', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Estação', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Estadia Gramado', 'Acre 116');
INSERT INTO hoteis (nome,telefone) VALUES ('Estalagem La Hacienda', '3286-8186');
INSERT INTO hoteis (nome,telefone) VALUES ('Estalagem Villa Suzana', '3282-87-87');
INSERT INTO hoteis (nome,telefone) VALUES ('Estrelas da Serra', '3286-2424');
INSERT INTO hoteis (nome,telefone) VALUES ('Estrelato', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Fazenda Hípica Santa Fé', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Flor de Canela- 3282-3420', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Florença', '3286-4754');
INSERT INTO hoteis (nome,telefone) VALUES ('Floresta Negra', '3282-3872');
INSERT INTO hoteis (nome,telefone) VALUES ('Galo Vermelho', '3286-1721');
INSERT INTO hoteis (nome,telefone) VALUES ('Giardino di Pietra', '3286-1210');
INSERT INTO hoteis (nome,telefone) VALUES ('Glamour da Serra', '3286-9692/3286-9645');
INSERT INTO hoteis (nome,telefone) VALUES ('Gramadense', '3295-2336');
INSERT INTO hoteis (nome,telefone) VALUES ('Gramado Hostel', '3295-1020');
INSERT INTO hoteis (nome,telefone) VALUES ('Gramado Master Palace', '3295.7171');
INSERT INTO hoteis (nome,telefone) VALUES ('Gramado Palace', '3286-2021');
INSERT INTO hoteis (nome,telefone) VALUES ('Gramado Parque Hotel', '3286-2588');
INSERT INTO hoteis (nome,telefone) VALUES ('Gramado Portal Hotel', '3286-6548/3286-6679');
INSERT INTO hoteis (nome,telefone) VALUES ('Grande Hotel Canela', '3282-1285');
INSERT INTO hoteis (nome,telefone) VALUES ('Grosshaus', '3286-9797');
INSERT INTO hoteis (nome,telefone) VALUES ('Hortênsias', '3286-1057');
INSERT INTO hoteis (nome,telefone) VALUES ('Hospedaria Gaúcha', '3278-1009');
INSERT INTO hoteis (nome,telefone) VALUES ('Hospedaria Provençal', '3282-6929');
INSERT INTO hoteis (nome,telefone) VALUES ('Hostel Britânico', '3286-6250');
INSERT INTO hoteis (nome,telefone) VALUES ('Hostel N. Petrópolis', 'Bom Pastor');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Berghaus', '3281.2053');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Canela', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Caracol', '3282-4030');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Carpe Vita', '3282-7804');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel em Nova Petropolis', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel em São Francisco', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel não confirmado', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Pequenino', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Petrópolis', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Pousada da Serra', '3286-2491');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Pousada Reviver', '3281-1096');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Pouso das Águias', 'Canela');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Provence', '3286-2552');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel San Francisco', '3295-1771');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Tissiane', 'Alta Vista');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Veneza Italia', '3286.1075');
INSERT INTO hoteis (nome,telefone) VALUES ('Hotel Veraneio Schoeler', '(54)3298 1052');
INSERT INTO hoteis (nome,telefone) VALUES ('Igreja de Canela', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Igreja Luterana', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Jardim Bella Vista', '3295-1906');
INSERT INTO hoteis (nome,telefone) VALUES ('Jardineira', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Kaster', '3295-2289');
INSERT INTO hoteis (nome,telefone) VALUES ('Kiss Me', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Kitty Hotel', '3286-8133');
INSERT INTO hoteis (nome,telefone) VALUES ('Klein Ville', '3278-2101');
INSERT INTO hoteis (nome,telefone) VALUES ('Klein Ville Gramado', '3282-5530');
INSERT INTO hoteis (nome,telefone) VALUES ('Kurotel', '3286-2133');
INSERT INTO hoteis (nome,telefone) VALUES ('La Lavande', '3286-4265');
INSERT INTO hoteis (nome,telefone) VALUES ('la vie en rose', '3282-7899');
INSERT INTO hoteis (nome,telefone) VALUES ('Ladeira', '3286-2953');
INSERT INTO hoteis (nome,telefone) VALUES ('Laghetto', '3295-6969');
INSERT INTO hoteis (nome,telefone) VALUES ('Laghetto Premium', '3286-1619');
INSERT INTO hoteis (nome,telefone) VALUES ('Laghetto Siena', '3295-9292');
INSERT INTO hoteis (nome,telefone) VALUES ('Laghetto Viale', '3295-5252');
INSERT INTO hoteis (nome,telefone) VALUES ('Laghetto Vivace Viale', '3295-5252');
INSERT INTO hoteis (nome,telefone) VALUES ('Laghetto Vivave Viale', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Laje de Pedra', '3278-9000');
INSERT INTO hoteis (nome,telefone) VALUES ('Le Chateau', '3286-6606');
INSERT INTO hoteis (nome,telefone) VALUES ('Letícia', '3286-1055');
INSERT INTO hoteis (nome,telefone) VALUES ('Lido POA', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Luar da Serra', '3286-5666');
INSERT INTO hoteis (nome,telefone) VALUES ('L´Hermitage', '3286-1270');
INSERT INTO hoteis (nome,telefone) VALUES ('magnum 84143245', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Mel', '3286-3046');
INSERT INTO hoteis (nome,telefone) VALUES ('Mercure Hotel Gramado', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Metodista', '3286-2299');
INSERT INTO hoteis (nome,telefone) VALUES ('Mikolay', '3286-2161');
INSERT INTO hoteis (nome,telefone) VALUES ('Mini Pousada', '3286-7151');
INSERT INTO hoteis (nome,telefone) VALUES ('Modevi (Dinda)', '3295-1075');
INSERT INTO hoteis (nome,telefone) VALUES ('Monte Felice', '3286-2229');
INSERT INTO hoteis (nome,telefone) VALUES ('Morada dos Anjos', 'Gramado');
INSERT INTO hoteis (nome,telefone) VALUES ('Motel Avenida', '3286-3552');
INSERT INTO hoteis (nome,telefone) VALUES ('Mundo Encantado', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Natur Hotel Balneário', '3286-1027');
INSERT INTO hoteis (nome,telefone) VALUES ('Niederauer', '3286-5590');
INSERT INTO hoteis (nome,telefone) VALUES ('Nossa Casa', '3286-4075');
INSERT INTO hoteis (nome,telefone) VALUES ('O Canto do Sabiá', '3282-2935');
INSERT INTO hoteis (nome,telefone) VALUES ('outro', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pampas da Serra', '3278- 0030');
INSERT INTO hoteis (nome,telefone) VALUES ('Papoulas', '3286-7150');
INSERT INTO hoteis (nome,telefone) VALUES ('Pássaros', '3286-6098');
INSERT INTO hoteis (nome,telefone) VALUES ('Paz – Janz Team (Casa de Retiro)', '3286-1006');
INSERT INTO hoteis (nome,telefone) VALUES ('Pequeno Bosque', '3286-1527');
INSERT INTO hoteis (nome,telefone) VALUES ('Pertuti', '3286-2513');
INSERT INTO hoteis (nome,telefone) VALUES ('Petit Casa da Montanha', '3295-1951');
INSERT INTO hoteis (nome,telefone) VALUES ('Pinha Pinhão', '3286-1367');
INSERT INTO hoteis (nome,telefone) VALUES ('Pinhão e Poesia', '3282-2609');
INSERT INTO hoteis (nome,telefone) VALUES ('Pinheiros', '3282-2503');
INSERT INTO hoteis (nome,telefone) VALUES ('Pórtico Hotel', '3286-1037');
INSERT INTO hoteis (nome,telefone) VALUES ('Potal do Vale', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Araucária', '3282-7282');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Baronesa', 'Nova Petropolis');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Baronesa', 'Nova Petropolis');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Caliandra', '3282-1558');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Camponesa', 'Nova Petropolis');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Canela', '3282-8410');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Carpe Vita 3278 0017', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Casa da Cica', '3286-3149');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Casa Primavera', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Cema', '3282-2900');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Cravo e Canela', '3282-1120');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada da Chácara', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada da Colina', '3286-7355');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada da Manu', '3282-6127');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada da Torre', '3286-7290');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Das Aguias', '3282-4477');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada das Águias', '3282-4477');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada das Flores', '3286-1841');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada das Sequoias', '3282-1373');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Di Bergamo 3282 6696', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada do Bosque', '3282-2522');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada do Conde', '3282-2888');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada do Lago', '3286-5547');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada do Serrano', '3295-5000');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada do Sonho', '3282-2669');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada do Verde', '3286-1506');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada do Viajante', '3282-2017');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Doce Canela', '3282-9229');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Dona Iracema', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada dos Pinheiros', '3282-2503');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Estância Suíça', '3282-1435');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Familiar', 'Nelson Antonioli');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Fênix- 9654-8045', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Gardênia', '3286-4203');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Girotto', '3282-1753');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Gramado', '-3286-1670');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Gramado dos Vales', '3286-2472');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Jardim Azul', '3282.4258');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Jardim Secreto', '3286-2023');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Jasmin', '3286-6382');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Katedral', '3282-6703');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Katedral', '32826703');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada La Lavende', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Lanai', '3295-1120');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Liriana', '3286-4923');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Mica N.P.', '3281.1793');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Monte Felice', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Nosso Lar', '3286.4356 / 3286.5698');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Pernoitar', '3286-6041');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Ruppenthal', '3282-3233');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Santa Maria do Herval', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Serrana', 'Nova Petrópolis');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Sol e Lua', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Sonho e Serra', '3282-1350');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Tia Eni', 'Bairro Pórtico');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Tia Erondina', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Tissiani', '3286.5590');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Vila Alegro-3282-9691', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Vila Suiça', '3282 1473 e 3282 3188');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Vila Suiça', '3282-1473');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Villa Cezar', '3282-1753');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Villa dos Gerânios-3295-1695', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Volta ao Mundo', '3282-3865');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Vovó Carolina', '3286-2679');
INSERT INTO hoteis (nome,telefone) VALUES ('Pousada Xixo Escultura', '3286 1625');
INSERT INTO hoteis (nome,telefone) VALUES ('Pouso das Águias', 'Canela');
INSERT INTO hoteis (nome,telefone) VALUES ('Querência', '3286-2104');
INSERT INTO hoteis (nome,telefone) VALUES ('Quinta dos Marques', '3282-9812');
INSERT INTO hoteis (nome,telefone) VALUES ('Raposa Vermelha', '3286-2214');
INSERT INTO hoteis (nome,telefone) VALUES ('Recanto Alpino', '3286-3744');
INSERT INTO hoteis (nome,telefone) VALUES ('Recanto da Ladeira', '3286-2953');
INSERT INTO hoteis (nome,telefone) VALUES ('Recanto da Lua', '3286-2463');
INSERT INTO hoteis (nome,telefone) VALUES ('Recanto da Natureza', '3286-8569');
INSERT INTO hoteis (nome,telefone) VALUES ('Recanto da Serra', '3286-2450');
INSERT INTO hoteis (nome,telefone) VALUES ('Recanto das Palmeiras', 'Nova Petrópolis');
INSERT INTO hoteis (nome,telefone) VALUES ('Recanto Suíço Nova Petrópolis', '(54) 3281-1229');
INSERT INTO hoteis (nome,telefone) VALUES ('Renascença', '3295-1762');
INSERT INTO hoteis (nome,telefone) VALUES ('Residencial Vale Dourado', '3286-9500');
INSERT INTO hoteis (nome,telefone) VALUES ('Restaurante Kilo e Kilo', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Rita Hoppner', '3286-1334');
INSERT INTO hoteis (nome,telefone) VALUES ('Rosa', '3286-4202');
INSERT INTO hoteis (nome,telefone) VALUES ('Saint Gottard', '3286-2636');
INSERT INTO hoteis (nome,telefone) VALUES ('San Clemente', '3286.1626');
INSERT INTO hoteis (nome,telefone) VALUES ('San Lucas', '3286-3600');
INSERT INTO hoteis (nome,telefone) VALUES ('Serra Azul', '3295-7200');
INSERT INTO hoteis (nome,telefone) VALUES ('Serra Nevada (Serra Verde)', '3278-9700');
INSERT INTO hoteis (nome,telefone) VALUES ('Serra Valle', '3286-4328');
INSERT INTO hoteis (nome,telefone) VALUES ('Serrano', '3295-8000');
INSERT INTO hoteis (nome,telefone) VALUES ('Serrano Flat', '3286-1332 ou 3295-8000');
INSERT INTO hoteis (nome,telefone) VALUES ('Sesc', '3286-0503');
INSERT INTO hoteis (nome,telefone) VALUES ('Sesi', '3282-1311');
INSERT INTO hoteis (nome,telefone) VALUES ('Sheraton POA', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Sítio Ecológico Etiel – Spa Etiel', '3286-8219');
INSERT INTO hoteis (nome,telefone) VALUES ('Sítio Quero-Quero', '3286-1892');
INSERT INTO hoteis (nome,telefone) VALUES ('Sky', '3286-4716');
INSERT INTO hoteis (nome,telefone) VALUES ('Sol', '3286-3116');
INSERT INTO hoteis (nome,telefone) VALUES ('Solar da Serra 3286-1026', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Solar da Serra Premiun', '3286- 7170');
INSERT INTO hoteis (nome,telefone) VALUES ('Sonho Meu', '3286-3075');
INSERT INTO hoteis (nome,telefone) VALUES ('Sonnenhof', '3286-7788');
INSERT INTO hoteis (nome,telefone) VALUES ('Sossego do Major', '3286-9697');
INSERT INTO hoteis (nome,telefone) VALUES ('St. Humbertus', '3286-1273');
INSERT INTO hoteis (nome,telefone) VALUES ('Sul Serra Hotel', '3286-1718');
INSERT INTO hoteis (nome,telefone) VALUES ('Sulla Collina', '3286-1651');
INSERT INTO hoteis (nome,telefone) VALUES ('Sun Moon', '3286-2680');
INSERT INTO hoteis (nome,telefone) VALUES ('Tango', '3295-1050');
INSERT INTO hoteis (nome,telefone) VALUES ('Tannenwald', '3286-4717');
INSERT INTO hoteis (nome,telefone) VALUES ('Tia Leonor', '3286-1146');
INSERT INTO hoteis (nome,telefone) VALUES ('Toca dos Ursos', '3286-1558');
INSERT INTO hoteis (nome,telefone) VALUES ('Toscana Gramado', '3295-9797');
INSERT INTO hoteis (nome,telefone) VALUES ('Vale do Bosque', '3286-3013');
INSERT INTO hoteis (nome,telefone) VALUES ('Vale do Quilombo', '3286-2394');
INSERT INTO hoteis (nome,telefone) VALUES ('Vale Dourado', '3286-9500');
INSERT INTO hoteis (nome,telefone) VALUES ('Varanda das Bromélias', '3286-6653');
INSERT INTO hoteis (nome,telefone) VALUES ('Veredas', '3278-2178');
INSERT INTO hoteis (nome,telefone) VALUES ('Via Serena', '3286-3394');
INSERT INTO hoteis (nome,telefone) VALUES ('Vida e Natureza', '3286-5466 / 9987-8117');
INSERT INTO hoteis (nome,telefone) VALUES ('Vila dos Geranios', '3295-1695');
INSERT INTO hoteis (nome,telefone) VALUES ('Vila Fioritta', '3282-2940');
INSERT INTO hoteis (nome,telefone) VALUES ('Vila Flor', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Vila Suzana', '3282-2020');
INSERT INTO hoteis (nome,telefone) VALUES ('Vila Vecchia', '3282-4220');
INSERT INTO hoteis (nome,telefone) VALUES ('Vila Verde Nova Petrópolis', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Villa Bella Gramado Hotel', '3286-2688');
INSERT INTO hoteis (nome,telefone) VALUES ('Village da Serra (São Francisco)', '3244.2853');
INSERT INTO hoteis (nome,telefone) VALUES ('Vista do Vale', '3286-1605');
INSERT INTO hoteis (nome,telefone) VALUES ('Vô Mário', '3295-1951');
INSERT INTO hoteis (nome,telefone) VALUES ('Vovó Anita', '3286-3877');
INSERT INTO hoteis (nome,telefone) VALUES ('vovo carolina', '');
INSERT INTO hoteis (nome,telefone) VALUES ('Vovó Carolina', '3286-2433');
INSERT INTO hoteis (nome,telefone) VALUES ('Zermatt', '3286-4111');

INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('4 Estações - Thiago e Edson', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('5 amigos Paulo, Evandro,Eduardo,Italo,Maximiliano', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('?', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Abel Sul Serra Sul Serra', 66, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Acácia Negra Acásia negra', 78, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Aconchego da Serra', 36, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Adelar Galo Vermelho Galo', 28, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Adriana - Sesc', 147, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Adriana CVC', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Adriano Brocker', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Adriano Pousada Bertoluci', 38, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Aeroporto', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ag Destak Taubaté', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ag. Altos da Serra', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ag. Grandes Viagens', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ag. Gute. Reise', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ag. Ilha Rocca', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ag. Interação', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ag. Netway', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Active', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Avenida', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência GBS', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Global Tur', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Hotéis Tur Poa', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agencia Mundo do Vinho', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Netway', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Quanta Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Terra Magia', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Tpatur', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Turmarine Turismo, Wilder', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Usytur', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência Vittório de N. Petrópolis', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agência/outro estado', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Agente da CVC de SP', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Águia Branca', 79, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alameda Paradiso Alameda', 234, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Albergo di Bezzi', 72, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ald Mamma', 180, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Aldeia dos Sonhos Aldeia do Sonho', 222, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alencar', 40, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alex Recanto Alex Recanto', 122, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alexandre - Galo Vermelho Galo Vermelho', 28, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alexandre Berti - Bella Terra', 84, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alexandre Hotel Continental', 152, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alexandre Lermitage Lermitage', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alexandre-Garfo Garfo', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alice', 201, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Aline', 81, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Aline - Patchwork Patchwork', 182, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alisson', 81, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Almir Kaster Ribeiro', 40, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alpen Park', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alpenhaus', 55, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alpes Verdes', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alpestre Alpesstre', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Alta Vista Alta Vista', 187, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Altivo - Pousada Vovó Carolina', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Altivo CVC CVC', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Amiga', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Amigo Moisés - Recife', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Amigos', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Amigos - Angela Alpestre', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Amigos e Agência WRT de Natal', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ana Claudia - Brocker', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Anderson Cabanas-Tio Muller', 17, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Anderson - R. da Lua Anderson Recanto da Lua', 123, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('anderson - st hubertus', 5, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Anderson San Lucas San Lucas', 42, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Andre Recanto da serra Andre recanto', 45, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('ANDREA', 9, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Anna', 28, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Antônio Galo Vermelho Antonio Galo', 28, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Antonio Linha Bella', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Araucárias-André André Araucarias', 257, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ardvark Inn - Guilherme', 252, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ari Stopassola Junior', 68, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ari SEM sobrenome Junior', 60, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('ARI TESTE EDITADO', 68, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Artur', 252, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Atitude', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Aureo Guia Aureo', 182, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Azaléia Adilvo/Carlos/Antenor/Márcio', 167, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Bangalos da Serra', 1, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Barbacovi', 37, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Beatriz - Ares Beatriz', 81, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Beatriz veneza casa veneza', 93, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Beatriz Veneza', 276, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Bernardete', 86, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Bertoluci', 38, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Betania -Vitor', 87, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Bibiana/Bavaria', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Biguncha', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Black Bear', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Blogs', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Blumenberger', 227, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Brilho da Serra', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Brisa da Serra avenida', 89, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Brisa de Gramado', 88, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Brocker Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Bruna - Hotel Leticia', 33, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Bruno - Ares da Serra', 81, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Byke Tour - Guilherme', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cabana Jardim das Flores', 14, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cabanas Alto da Serra- Edson Alto da Serra', 217, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cabanas da Mata', 100, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cabanas Rota do Sol', 15, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cabanas Tio Chico', 16, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Café com leite', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Camila Alpenhaus', 55, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Camile - Alpestre', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Caminhos Tur', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Canto Verde', 19, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Caracol', 228, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Caren', 81, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Carina - Beija Flor', 83, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Carina Galo', 28, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Carlão -terra', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Carlos Arend - Alpestre', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Carlos La Vie en Rose', 210, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Carol - Pinhão e Poesia', 236, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cartão Vip', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Casa Branca', 87, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Casa da Montanha Casa da Montanha', 20, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('CASA DO COLONO', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Casa Rosa', 148, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Casa Rosa', 148, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Casa Valduga', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cassio - Bernardete Pousada Bernardete', 86, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cauê Pipoca', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Célio - Sul Brasil Sul Brasil', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Celita', 97, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Central Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cesar -Serrano', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('César Canto Belo', 18, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Chocolate do Parque', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Chocolate Lugano', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Chocolate Park', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cica', 271, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cinema', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cirion-San Lucas San Lucas', 42, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('CIT', 182, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('CIT Jonas CIT', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Citral - Amiga da Iris (Kelly)', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Clarissa Giradino', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Claudemir - Bavaria', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Claudia - Colina', 98, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cláudia - P. Assefaz', 82, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cleber - Cabanas da Mata', 100, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cleber Alpenhof Mello', 9, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cleberson Lima De Andrade', 28, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cleiton Frank', 121, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cliente', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Colina de Pedra', 3, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Continental', 152, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Convention - Luciano', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Crepe - Noeli', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cristian Encantos do Sul', 25, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cristiano san Lucas San Lucas', 42, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cristina Lagueto Laghetto', 32, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Cunhado', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('CVC', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('CVC Gramado - Neka', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('D. Alice', 201, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Daniela-CVC', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Dauras Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Delmar Alpestre Loesch', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Dentista', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Di Marco', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Diego', 156, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Diego vila Bela', 68, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Diogo Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Dionisio Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Dirceu', 7, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Disolle', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Don Ramon Don Ramon', 247, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Duda Duda', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Dyhonatan Alpestre Ruschell', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('ECO SERRA', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Edelweiss', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Edgar Vale das Vinhas', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Edmilson terra turismo Terra', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Eduardo - Colina', 98, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Eduardo Bavaria bavaria', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Eduardo Pousada Colina', 98, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Eko Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Eko turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Elisandra - Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Elmer - San Lucas', 42, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Eloir Lira Due Fratelli', 109, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Em Gramado', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Emerson', 258, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Encantos Charme Hotel', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Encantos de Gramado', 110, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Encosta', 99, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Equipe Sky', 50, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Essenza', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Estalagem Villa Suzana Estalagem Villa Suzana', 150, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Estevan-vida Livre', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Estrelas da Serra', 26, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('EVANDRO', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Evandro Bavaria', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Everson - Pousada Vovó Carolina', 140, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Everton - Galo Vermelho', 28, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Everton Alexandre', 28, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ezequiel - Esquilo', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Fabiano - Kilo&Kilo', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Fabiano Alpenhaus motorista', 55, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Fabio Bavária Davides', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Fabio Junior Sul Serra Pereira Souza', 66, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('fabio pousada vovo carolina', 140, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Facebook', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Familiares', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Farmácia São João', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Felipe Galo Vermelho', 28, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Felipe Brisa da Serra', 89, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Felipe Gatelli - Bella Terra', 84, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Fernanda - Encosta', 99, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Fernanda - Galo Vermelho', 28, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Fernanda Fioreze', 74, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Filha', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Filho', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Flavia Giardino Di Pietra', 29, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Florença', 111, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Folder Águas Claras', 7, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Folder Alpestre', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Folder Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Folder Galo Vermelho', 28, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Folder Gramado Parque Hotel', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Folder Hotel', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Folder Mini Mundo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Folder Mundo à Vapor', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Folder Pórtico Hotel', 62, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Folder Vila Vecchia', 231, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Foto Real - Kodak', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Front Eventos', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Fumacinha', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Galeto Italia', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Galvão Brocker', 226, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('GB TOURS', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Gebrail-Lagheto Vivace viale', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Gerônimo - CVC', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Geronimo Xuxa', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Giardino di Pietra', 29, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Gilberto / Capucho', 182, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Gilmar Glamour da Serra', 151, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Giordani', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Gislei Vista do Vale', 166, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Glaucia - Chocolate do Parque', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Google', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Graça Tur BH', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Gramado Palace', 30, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Gramado Portal', 285, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('gramado site', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Gramadosite', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('GRUPON ANDRÉ', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('GUIA 4 RODAS', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Guia Brocker', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('guia serras gaúchas', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Guia Zenaide', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Guilherme - Pai Leandro', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Guilherme Liga Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('H. Encantos do Sul', 25, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hangar Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hangar Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Henrique Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Henrique Vovó Carolina', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Henrique Vovó Carolina', 54, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hostel Hostel', 76, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Aguas Claras', 7, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Alpenhof', 9, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Alpestre', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Alpestre', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Auberge', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Canto Belo', 18, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel canto verde', 19, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Caracol', 228, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Cavalo Branco', 21, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel das Hortênsias', 22, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Estrelas da Serra', 26, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Fellini POA', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Galo Vermelho', 28, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Leticia', 33, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Pequenino', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Pórtico', 62, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Querencia', 44, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Rita Hoppner', 158, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Serrano', 48, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('hotel sky sky', 50, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Sonnenhof', 131, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Sul Serra', 66, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Tissiane - Alta Vista', 307, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('HOTEL TOSCANA TOSCANA', 60, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Varanda', 67, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Villa Bella', 68, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Vô Mário', 53, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Hotel Vovó Carolina', 54, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('HS', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Humberto', 25, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Icléa - Pousada do Lago', 241, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ilse Colina Hoff Pinheiro', 98, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Incentivare', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Internet', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Irani', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Irmã', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Irmão', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Irmao', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Isabel - Hotel San Francisco', 303, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Isabel Solar da Serra', 225, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('italo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Italo Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ivo Lopes - P. Vovó Carolina', 140, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ivo Lopes - P. Vovó Carolina', 140, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('IVO/JULIO', 140, 'n');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ivonete e João Carlos Ivonete e João Carlos', 320, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('já conhecia', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jackson Peccatto', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jackson-Boteco', 182, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jairton - Kilo Kilo', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Janaina - Pousada Gardênia', 287, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jardim Azul', 310, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jardim Secreto - Jardim Secreto', 308, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jardim Secreto - Jardim Secreto', 308, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jardineira', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jeferson - P. Vovó', 140, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('jeferson agguas Claras', 7, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jeferson Fioreze - P. das Flores', 207, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jesus', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('JM Rafting', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('João - Encantos do Sul', 25, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('João - Pousada do Verde', 208, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('João - Sonnenhof', 131, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('João Carlos - Bavaria', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('João-Restaurante', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jocelino', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Joel - San Lucas', 42, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jonas - Badanha', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jonas - Hotel Leticia', 33, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jonas - Sonnenhof', 131, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jonas hofman Hofman', 303, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jonatan Glamour Ribeiro Franco', 151, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Jonatham Bavaria Bavaria', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('jornal, revista, tv', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Josi - Galo Vermelho', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Josimar - Propagtur', 156, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Josué - Kaster', 40, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Juliano-Locadora', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Julio - P. Vovó Carolina', 140, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Karina Casa Rosa Oliveira', 148, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Kaster', 40, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Klein Ville', 164, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Kruse Turismo POA', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Laghetto Premium', 289, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Laghetto Siena Laghetto Siena', 246, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Laram Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Larissa - Solar Sumidade ROLDO', 130, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Leonardo San Lucas', 42, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Leonardo Tissot - D. Inácio Turismo', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Lisi - Azulzinha', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Lourdes Assefaz', 82, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('lourdes Ruckhaber Casa Dutra', 322, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Luan', 28, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('luan galo', 28, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Luana - Princesinha', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Luar da Serra', 116, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Lucas', 236, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Lucas - Florença', 111, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Lucas - Recanto da Lua', 124, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Lucas - Recanto da Lua Recanto da Lua', 124, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Lucas - Sulla Colina', 132, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Lucas Alpenhaus', 55, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Lucio-CVC', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Maciel Recanto da Lua', 124, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Mãe', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Maiara - Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Maico - Vecchia Fotografia', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Maico belluno Basei Rossa', 85, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Manguetur', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcela Alpestre Renata', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcelo - Master', 325, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcelo - Pousada Bertoluci', 38, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcelo Benetti', 81, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcelo Continental Pereira Guterres', 152, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcelo Oliveira - Recanto da Serra', 45, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcelo Viana - Recanto da Serra', 45, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcia - Sonnenhoff - Entregar de manhã', 131, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Márcia CVC', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcio - Serra Verde', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Márcio Silva', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcos - São Lucas', 42, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marcos Villa Bella', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Margarida - Recanto Suíço N. Petr.', 326, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Margarida sossego Sossego do Major', 43, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Maria Alice - Encantos do Sul', 25, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Maria Helena-Brocker', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marido', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Mario Gritti', 81, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Marli - Alpestre', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Mateus - Missioneira', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Mateus - Serra Valle Serra valle', 129, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Mateus Terra', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Mateus Tio Müller Leobet', 17, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Matias - Estrelas Magnus', 26, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Mauricio - CVC', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Maurício Canto Belo Fioreze', 18, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Mauricio natur Mauricio Natur', 59, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Mauro Encantos da Terra Pereira Salles', 175, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Mayara Bavaria', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('MG Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Miguel - Sossego do Major', 43, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Miguel-Sul Serra Sul Serra', 66, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Miolo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Moacir Franke Pinha Pinhão', 121, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Moisés amigo Recife', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('morador', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Muriel - Vista do Vale', 166, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Nailor Balzaretti', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Não lembra', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Natali (folder)', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Natur Hotel', 59, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('NeriRecanto Neri', 45, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Niderauer', 118, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Nilson', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Nilson - San Clemente', 128, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('NOSSO CLIENTE', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Nosso Lat', 267, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Odilon', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Oliveira', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Orkut', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Oscar', 86, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('P. Mica N.P.', 251, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Padaria São Pedro', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pai', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Palácio dos Festivais - Cinema', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Paraíba', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Parente', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Parentes', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Passando', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pássaros', 108, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pato Rocco', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Patrão / Chefe / Patroa', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Paulo - Zé Candinho', 182, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Paulo Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Paulo Carlitos', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Paulo/Luciana - Serra Verde', 189, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pedrinho', 54, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pedro - Pinha Pinhão', 121, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pedro Land', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pequeno Bosque', 35, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Petit - Casa da Montanha', 295, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pinha Pinhão', 121, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pinhão e Poesia - Augusto', 236, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Porto Van', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Rosa', 126, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Bella Terra', 84, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Bernardete', 86, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Betania', 87, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Canela Pousada Canela', 184, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Cema', 249, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada da Colina', 248, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada das Sequóias Pousada das Sequóias', 211, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Di Bergamo Pousada Di Bergamo', 283, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada do Bosque', 195, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada do Conde', 274, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada do Serrano', 63, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada do Sonho Pousada do Sonho', 240, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada do Verde', 208, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Doce Canela Doce Canela', 311, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada dos Anjos', 149, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Gardênia', 287, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Gramadense', 112, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Gramado', 256, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Grosshaus', 114, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Jasmin - Solar Sumidade', 130, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Jasmin - Solar Sumidade - 3286-2056', 130, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Le Chateau', 41, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Nosso Lar', 267, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Rosa', 126, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Ruppenthal', 265, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Sonho e Serra - Ciliandra', 255, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Sulla Collina Ltda Sergio basei', 132, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Tia Eni', 318, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Tia Leonor', 135, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Tissiani', 300, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Veredas', 223, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Pousada Vovó Carolina', 140, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Prima', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Proprietário da casa', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rafa - Continental', 152, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rafael Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rafael JM Rafting', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rafael Rech - Bertoluci', 38, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Raquel', 308, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Raul de Souza', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Recanto da Ladeira', 123, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Recanto da Lua', 124, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Recanto da Serra', 45, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Renato Schulz Renato', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ricardo - Aldeia dos Sonhos', 222, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ricardo Aldeia dos Sonhos Aldeia dos Sonhos', 222, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rita Hoppner', 158, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('RJR Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rodoviária', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rodrigo - Recanto da Serra', 45, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rodrigo Ruckhaber - Pousada Vovó', 140, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rogério Schulz', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rogério Sergipe', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ronaldo Brocker', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ronaldo CITRAL', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ronaldo Gramado Tour Privativo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rosa Mosqueta', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rose Hospedaria Provençal', 229, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Roseli Encantos do Sul', 25, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rosvita', 117, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rota Sul', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rota Sul 52', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rovilho', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rubens - Sossego do Major', 43, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rubens - Sossego do Major', 43, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Rúbia e Márcio - Cantinho do Sossego', 230, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Saint Gottard', 127, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('San Clemente', 128, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('San Lucas', 42, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Sebastião Melo', 258, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Sérgio - Vídeo', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Serra Azul', 181, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Serra Valle', 129, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Serra Verde', 189, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Sesc', 147, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Sheila - Galo Vermelho', 28, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ship Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Silvana - Casa de Veneza', 93, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Silvana - Encantos do Sul', 25, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Silvana - Veneza Italia', 276, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Silvano-Citral - 9902.4644 Santos - Citral', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Simone - CIT CIT', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Sissi - Jardim Secreto', 308, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Site Férias Brasil', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Site Mochileiros', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Site Prefeitura de Gramado', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Sítio Quero-Quero - Felipe Fioreze', 49, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Solar da Serra', 225, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Sônia - Pinha Pinhão', 121, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Sonnenhoff', 131, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Sr. Guilherme', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('St. Humbertus', 5, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Sun Power', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tango', 134, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tarantino', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tatiana - Bavária', 13, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tatim CVC', NULL, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Taxi', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Taylor guia Taylor', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Terminal guia', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Terra Turismo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Thiago Basei - Hotel São Francisco', 303, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tia Iracema', 321, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tia Leonor', 135, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tiago Baum', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tiago Cavallin/João Carlos Theisen - H. Vovó Carolina', 54, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tiago Sossego do Major', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('tiago via serena via serena', 294, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tio Bernardo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tios', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tissiane Canela', 300, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Toca dos Ursos', 136, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tomate - Fabiano Tomate', 186, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tonico', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('TOUR NATAL LUZ - ANA PAULA', 156, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('TOUR NATAL LUZ - MANO', 156, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tratoria restaurante', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Tribeca', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Trip Advisor', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Trip Serra Gaúcha', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Ursula', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vagner - Serra Valle Serra Valle', 129, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Valdecir Cantini - H. Vovó Carolina', 54, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vale das Vinhas', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vale do Bosque', 137, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vale do Quilombo', 138, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Valério CVC', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vanessa - Assefaz', 82, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vanessa Dinnebier Dinnebier', 76, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('vendo a Van adesivada', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vera serra Valle Serra Vale', 129, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Via Mondo', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Via Serena', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Viajante', 194, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vida Livre', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vila Alegro Vila Alegro', 323, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vila dos Geranios', 191, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vila Vecchia', 231, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Villa Bella', 68, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vista do Vale Vista do Valle', 166, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Vovó Anita', 139, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Wiliam Ald Mamma William ald Mamma', 180, 'n');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Wilian Villa Bella Villa Bella', 68, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Willian Goulart - Ex-Quero Quero', 186, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('WS Viagens', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Xaxa', 156, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Xixo', 293, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('XUXA CVC', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Zaca Tur', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Zé Candinho', NULL, '');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('zé Luis ex pousada do Serrano 9971.9508', NULL, 'n');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('Zélia', 119, 's');
INSERT INTO colaboradores (nome,id_hotel,ativo) VALUES ('zermatt', 141, '');